spring.application.name=attend_backend

# ===== DATABASE =====
spring.datasource.url=jdbc:postgresql://localhost:2005/attendx_db
spring.datasource.username=postgres
spring.datasource.password=YOUR_PASSWORD_HERE

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===== SERVER PORT =====
server.port=8080

# ===== JWT SECRET =====
jwt.secret=attendx_super_secret_key_2025_do_not_share
jwt.expiration=86400000